steps:
  # 1. Docker 이미지 빌드
  - name: 'docker'
    args:
      - 'build'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/greentech_globalthon_nodejs:latest'
      - '.'

  # 2. Docker 이미지 푸시
  - name: 'docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/greentech_globalthon_nodejs:latest'

  # 3. Deploy Docker Compose
  - name: 'gcr.io/cloud-builders/docker-compose'
    args:
      - 'up'
      - '-d'

# 권장: 빌드 후 출력된 이미지를 저장하는 태그
images:
  - 'gcr.io/$PROJECT_ID/greentech_globalthon_nodejs:latest'